---
- name: Create factorio user
  become: True
  user:
    name: "{{ factorio_user }}"
    group: "{{ factorio_group }}"
    groups: docker
    system: True
    uid: 845
    shell: /bin/bash
  register: created_factorio_user

- name: Create Factorio directories
  become: True
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ factorio_user }}"
    group: "{{ factorio_group }}"
  loop:
    - /opt/factorio
    - /opt/factorio/mods

- name: Setup mods
  become: True
  template:
    src: mod-list.json.j2
    dest: /opt/factorio/mods/mod-list.json
    owner: "{{ factorio_user }}"
    group: "{{ factorio_group }}"

- name: Setup docker-compose.yml
  become: True
  become_user: "{{ factorio_user }}"
  template:
    src: docker-compose.yml.j2
    dest: "{{ created_factorio_user.home }}/docker-compose.yml"

- name: Start container
  become: True
  become_user: "{{ factorio_user }}"
  docker_compose:
    project_src: "{{ created_factorio_user.home }}"
    state: present

- name: Setup factorio update service
  become: True
  template:
    src: update-factorio.service.j2
    dest: /etc/systemd/system/update-factorio.service

- name: Setup factorio update timer
  become: True
  template:
    src: update-factorio.timer.j2
    dest: /etc/systemd/system/update-factorio.timer

- name: Enable and start timer
  become: True
  service:
    name: update-factorio.timer
    state: restarted
    enabled: True
