---
- name: Create Factorio directories
  file:
    path: "{{ item }}"
    state: directory
    owner: '845'
    group: '845'
  loop:
    - /opt/factorio
    - /opt/factorio/mods
  become: True

- name: Setup mods
  template:
    src: mod-list.json.j2
    dest: /opt/factorio/mods/mod-list.json
    owner: '845'
    group: '845'
  become: True

- name: Create docker-compose directory
  file:
    path: "{{ created_user.home }}/factorio"
    state: directory

- name: Setup docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ created_user.home }}/factorio/docker-compose.yml"

- name: Start container
  docker_compose:
    project_src: "{{ created_user.home }}/factorio"
    state: present

