---
- name: Create Factorio directory
  file:
    path: /opt/factorio
    state: directory
    owner: '845'
    group: '845'
  become: True

- name: Create docker-compose directory
  file:
    path: "{{ created_user.home }}/factorio"
    state: directory

- name: Setup docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ created_user.home }}/factorio/docker-compose.yml"

- name: Start container
  docker_compose:
    project_src: "{{ created_user.home }}/factorio"
    state: present

