---
- name: Create factorio user
  become: True
  user:
    name: "{{ factorio_user }}"
    group: "{{ factorio_group }}"
    system: True
    uid: 845

- name: Create Factorio directories
  become: True
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ factorio_user }}"
    group: "{{ factorio_group }}"
  loop:
    - /opt/factorio
    - /opt/factorio/mods

- name: Setup mods
  become: True
  template:
    src: mod-list.json.j2
    dest: /opt/factorio/mods/mod-list.json
    owner: "{{ factorio_user }}"
    group: "{{ factorio_group }}"

- name: Create docker-compose directory
  file:
    path: "{{ created_user.home }}/factorio"
    state: directory

- name: Setup docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ created_user.home }}/factorio/docker-compose.yml"

- name: Start container
  docker_compose:
    project_src: "{{ created_user.home }}/factorio"
    state: present

