---
- hosts: localhost
  roles:
    - provision

- hosts: factorio
  gather_facts: no
  tasks:
    - name: Check SSH connection
      wait_for_connection:
        timeout: 3
      ignore_errors: True
      register: check_ansible_connection
    - name: Create User if not exists
      block:
        - wait_for_connection:
            timeout: 30
        - include_role:
            name: user
          vars:
            username: "{{ lookup('env', 'USER') }}"
      when: check_ansible_connection is failed
      remote_user: root

- hosts: factorio
  become: True
  roles:
    - security

