---
- hosts: localhost
  roles:
    - provision

- hosts: factorio
  gather_facts: no
  tasks:
    - name: Check SSH connection
      wait_for_connection:
        timeout: 3
      ignore_errors: True
      register: check_ansible_connection
    - name: Create User if not exists
      block:
        - wait_for_connection:
            timeout: 30
        - include_role:
            name: user
      when: check_ansible_connection is failed
      remote_user: root
    - name: Update User
      block:
        - include_role:
            name: user
      when: check_ansible_connection is not failed
      become: True

- hosts: factorio
  roles:
    - security
    - role: docker
      become: True
    - factorio

