---
- hosts: localhost
  roles:
    - provision_vultr

- hosts: factorio
  gather_facts: no
  remote_user: root
  tasks:
    - wait_for_connection:
        timeout: 30
    - include_role:
        name: user
