---
- name: Create user
  user:
    name: "{{ username }}"
    groups:
      - sudo
    append: True
    shell: /bin/bash
  register: created_user

- name: Get Vultr SSH keys infos
  vultr_ssh_key_info:
  register: vultr_ssh_keys

- name: Set authorized keys from Vultr
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ vultr_ssh_keys.vultr_ssh_key_info | selectattr('name', 'in', ssh_keys) | map(attribute='ssh_key') | join('\n') }}"
    exclusive: True
  vars:
    ssh_keys:
      - frank@archlinux
      - frank@carbon

- name: Disable requirement of sudo password
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

