---
- name: Create user
  user:
    name: "{{ username }}"
    groups:
      - sudo
    append: True
    shell: /bin/bash
  register: created_user

- name: Set authorized keys
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ authorized_keys | join('\n') }}"
    exclusive: True

- name: Disable requirement of sudo password
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

