---
- name: Create user
  user:
    name: "{{username}}"
    groups:
      - sudo
    shell: /bin/bash

- name: Set authorized key from file
  authorized_key:
    user: "{{username}}"
    key: "{{ lookup('file', '/home/' + username + '/.ssh/id_ecdsa.pub') }}"

- name: Disable requirement of sudo password
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

