---
- name: Install fail2ban
  apt:
    name: fail2ban

- name: Ensure fail2ban is enabled and started
  service:
    name: fail2ban
    state: started
    enabled: True

- name: Import SSH hardening
  include_role: dev-sec.ssh-hardening

- name: Import OS hardening
  include_role: dev-sec.os-hardening
