version: '2'
services:
  factorio:
    container_name: factorio
    image: factoriotools/factorio
    ports:
     - "34197:34197/udp"
    volumes:
     - /opt/factorio:/factorio
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - UPDATE_MODS_ON_START=true
#      - USERNAME=FactorioUsername
#      - TOKEN=FactorioToken
