---
- name: Install Docker
  include_role:
    name: geerlingguy.docker
  vars:
    docker_users:
      - "{{ created_user.name }}"

- name: Install pip
  apt:
    name: python3-pip

- name: Install docker python module
  pip:
    name:
      - docker
      - docker-compose
    state: present
